# disko disk layout for a typical VPS — single disk, GPT, EFI boot, ext4 root.
#
# Adjust `device` to match your VPS disk (check with `lsblk` on the target).
# Common values: /dev/vda (KVM), /dev/sda (Xen/older), /dev/nvme0n1 (NVMe).
#
# This file is used by nixos-anywhere for automated installation.
# For a manually-installed host, remove this import from flake.nix and use
# hardware-configuration.nix generated by `nixos-generate-config` instead.

{ ... }:

{
  disko.devices = {
    disk.main = {
      device = "/dev/vda";  # ← adjust to your VPS disk
      type = "disk";
      content = {
        type = "gpt";
        partitions = {
          boot = {
            size = "512M";
            type = "EF00";  # EFI System Partition
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
              mountOptions = [ "umask=0077" ];
            };
          };
          root = {
            size = "100%";
            content = {
              type = "filesystem";
              format = "ext4";
              mountpoint = "/";
              mountOptions = [ "noatime" ];
            };
          };
        };
      };
    };
  };
}
